### PR TITLE
`bagad2022reproducibility`

### PR DESCRIPTION
**Pull request by bpiyush**
## Reproducibility study of "Counterfactual Generative Networks"

Write the `bagad2022reproducibility` here, and as well as rename the PR name to reflect the `<paper_citekey>` for quick reviewing. 

## Compiled PDF

Add the link to the compiled pdf here. Example : [Compiled Pdf](https://github.com/bpiyush/MLRC/raw/main/2021/bagad2022reproducibility/journal/article.pdf)

## Metadata Checklist

Ensure that you have added the following metadata information (put an x to the checkbox items) in `<paper_citekey>/journal/metadata.yaml`.

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

## Build Errors

If your build had any errors locally, please add it here. You can upload your build.log in a [Pastebin](https://pastebin.com/) link and put it here.
* [Build logs](https://pastebin.com/kZHrvwZv)

### CODE REVIEW

**Comment by bpiyush** [comment]
@koustuvsinha Hi! So we had a few questions.

1. We want to add a note on equal contribution. How do we do that? We couldn't find a natural way through the template.
2. On my system, the latex build worked fine. But when my co-authors tried to pull my repo and run `./build_all.sh`, they got errors (logs below). Any hints on what could be wrong here?

image

**Comment by koustuvsinha** [comment]
Hi @bpiyush,

- You can add a new affiliation with name "Equal Contribution" and address "  " (two blanks). Check #45 
- Your co-author did not clone including all submodules. Try `git submodule update --init --recursive` in the cloned folder.

**Comment by bpiyush** [comment]
@koustuvsinha Alright, I added the equal contribution bit. Thanks for the tip.

Have asked my co-authors to try the fix you suggested. Thanks!

**Comment by bpiyush** [comment]
Hi @koustuvsinha ,
We are facing an issue in running `./build_all.sh` at our end. The brief error log is as follows:
```bash
------------
Running 'make "article.bbl"'
------------
make[1]: *** No rule to make target `article.bbl'.  Stop.
Rule 'biber article': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'article.bcf'
------------
Run number 1 of rule 'biber article'
------------
------------
Running 'biber  "article.bcf"'
------------
Latexmk: Found biber source file(s) [article.bcf bibliography.bib]
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 8 citation(s)
Collected error summary (may duplicate other messages):
  biber article: Command for 'biber article' gave return code 2
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
make: *** [article.pdf] Error 12
Build complete
```

We thought something in the code changed and could be causing this, but we went back to two older commits that had working code and it still does not work. Could you please help us figure this out? Maybe something in our environment?

The detailed terminal error logs are [here](https://pastebin.com/vDPdHiAE).

**Comment by bpiyush** [comment]
Kindly ignore the above issue regarding compilation. Maybe something in my VSCode was broken and restarting helped. The latest commit has a working PDF.

**Pull request merged**
