### PR TITLE
eijkelboom2022reproduction

### PR DESCRIPTION
**Pull request by ObviouslyLuuk**
## Project Name

eijkelboom2022reproduction

## Compiled PDF

not able to compile yet

## Metadata Checklist

Ensure that you have added the following metadata information (put an x to the checkbox items) in `<paper_citekey>/journal/metadata.yaml`.

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

## Build Errors

build_all.sh won't run at all:
./build_all.sh: line 11: make: command not found

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Hi @ObviouslyLuuk , can you let me know which platform you are using? In MacOS, you need to install [XCode command line tools](https://stackoverflow.com/questions/14671021/bash-make-command-not-found), or in Ubuntu you need to install [build-essential](https://askubuntu.com/questions/192645/make-command-not-found#753113).

**Comment by ObviouslyLuuk** [comment]
> Hi @ObviouslyLuuk , can you let me know which platform you are using? In MacOS, you need to install [XCode command line tools](https://stackoverflow.com/questions/14671021/bash-make-command-not-found), or in Ubuntu you need to install [build-essential](https://askubuntu.com/questions/192645/make-command-not-found#753113).

Hi, I'm using Windows :)

**Comment by koustuvsinha** [comment]
It seems in Windows you need to use the `chocolatey` package manager: https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows

**Comment by ObviouslyLuuk** [comment]
Hi @koustuvsinha, I now see the last commit has passed the checks but I don't see a way to manually check if the pdf is okay. Locally, the ./build_all.sh did not produce a correct pdf (the references did not work) so I am worried this might be the case here

**Comment by ObviouslyLuuk** [comment]
Hi @koustuvsinha, our last commit, two days ago, should've fixed all issues. However, there's still no checkmark, does this mean there's a problem?

**Comment by koustuvsinha** [comment]
Hi @ObviouslyLuuk, no it is just that every CI run has to be manually approved by us before it runs. I have started a run now!

**Comment by koustuvsinha** [comment]
Hi @ObviouslyLuuk, there is an issue with the compilation. You are using `\footref` but it is not defined. Please import the following package for the compilation to work:

```
\usepackage{footmisc}
```

**Comment by ObviouslyLuuk** [comment]
> Hi @ObviouslyLuuk, there is an issue with the compilation. You are using `\footref` but it is not defined. Please import the following package for the compilation to work:
> 
> ```
> \usepackage{footmisc}
> ```

Hi! Thank you for letting me know, I've updated it now

**Pull request merged**
