### PR TITLE
wilschut2022reproducibility

### PR DESCRIPTION
**Pull request by thomas-w-nl**
## Project Name

wilschut2022reproducibility

## Compiled PDF

The compiled PDF has errors.
 [Compiled Pdf](2021/wilschut2022reproducibility/journal/article.pdf)

## Metadata Checklist

Ensure that you have added the following metadata information (put an x to the checkbox items) in `<paper_citekey>/journal/metadata.yaml`.

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

## Build Errors

The compiled Pdf has some errors that we could not fix after following the steps.

- Editors info overlap with text
- References and citations do not work
- Bibliography is not printed

If your build had any errors locally, please add it here. You can upload your build.log in a [Pastebin](https://pastebin.com/s6f8GnMx) link and put it here.

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Hi, we will check the issue shortly. In the meantime, please fix your PR as it modifies one file from `2020` folder - you should only modify files within your own folder. Thanks!

**Comment by thomasvanorden** [comment]
We tried to fix the issue with the 2020 folder!

**Comment by koustuvsinha** [comment]
Hi @thomasvanorden, you were using `\loss` which wasn't defined. Add this to your `packages.tex` to make the compilation work:

```
\newcommand{\loss}{\mathbb{L}}
```

**Comment by thomasvanorden** [comment]
Hi @koustuvsinha, thank you for your comment. We added the line of code to the packages.tex! The pdf should compile correctly now.

**Pull request merged**
