### PR TITLE
korporaal2022replication

### PR DESCRIPTION
**Pull request by Gijsvanmeer**
## Project Name

`korporaal2022replication` 

## Compiled PDF

 [Compiled Article](2021/korporaal2022replication/journal/article.pdf)

## Metadata Checklist

Ensure that you have added the following metadata information (put an x to the checkbox items) in `korporaal2022replication/journal/metadata.yaml`.

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

## Build Errors

Some warnings remained and are shown in the [Build log](https://pastebin.com/G2gRaymw/), we are not exactly sure what to do about them (or if they matter).

### CODE REVIEW

**Comment by SharathRaparthy** [comment]
@Gijsvanmeer Can you please make sure to double-check the last point on the checklist? I am locally checking your PR and in the generated PDF, I see that the date entries are not empty.

**Comment by Gijsvanmeer** [comment]
@SharathRaparthy we emptied the contributors, dates, article and journal fields now and uploaded the new PDF to with these changes. If anything else needs changing please let us know.

**Comment by SharathRaparthy** [comment]
Thanks! Looks great to me.

**Comment by koustuvsinha** [comment]
@SharathRaparthy how did you ok this PR? this PR doesn't even have the content.tex files added! I'm unable to compile this project!

**Comment by koustuvsinha** [comment]
@Gijsvanmeer please create a new Pull Request from the main branch and add all the source files from your folder - currently we are missing the `content.tex` file from openreview folder so we cannot compile your project locally. Please look into this as soon as possible, else we won't be able to publish your work.

**Comment by Gijsvanmeer** [comment]
Hello @koustuvsinha I added a new pull request with the files attached. Sorry for the inconvenience.

**Comment by koustuvsinha** [comment]
Thanks so much @Gijsvanmeer for the quick response!! I confirm everything works now!

**Comment by koustuvsinha** [comment]
Fixed in PR #113

**Pull request merged**
