### PR TITLE
panigrahi2022re

### PR DESCRIPTION
**Pull request by sibasmarak**
## Compiled PDF

[Compiled Pdf](https://github.com/sibasmarak/MLRC/blob/main/2021/panigrahi2022re/journal/article.pdf)

## Metadata Checklist

Ensure that you have added the following metadata information (put an x to the checkbox items) in `panigrahi2022re/journal/metadata.yaml`.

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

## Build Errors

If your build had any errors locally, please add it here. You can upload your build.log in a [Pastebin](https://pastebin.com/) link and put it here.

### CODE REVIEW

**Comment by sibasmarak** [comment]
@koustuvsinha we have followed all the steps mentioned in the README and also completed the 11 tasks mentioned in the PR comment. However, there is a small issue that we are facing - we need to run `build_all.sh` script twice to get the desired `article.pdf`. The first time, a blank pdf is generated - any reason for this behavior?

**Comment by koustuvsinha** [comment]
Hi @sibasmarak , it works on first try for me!

**Comment by sibasmarak** [comment]
Hi @koustuvsinha!
Thank you for checking it out. Do we need to do anything else now, or will you verify and merge the branch?

**Comment by koustuvsinha** [comment]
This would be all, thanks! We will rebuild the paper with the journal publication details.

**Pull request merged**
