### PR TITLE
nalmpantis2022re

### PR DESCRIPTION
**Pull request by din0s**
## Project Name

**nalmpantis2022re**: `[Re] Exacerbating Algorithmic Bias through Fairness Attacks`

## Compiled PDF

[Compiled PDF](2021/nalmpantis2022re/journal/article.pdf)

## Metadata Checklist

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

## Build Errors

Latexmk: Missing bbl file 'article.bbl' in following:
 No file article.bbl.
make[1]: *** No rule to make target 'article.bbl'.  Stop.

However, the PDF was generated successfully, so it might be ok regardless.

### CODE REVIEW

**Comment by SharathRaparthy** [comment]
@din0s Could you please make sure `./build_all.sh` compiles without any errors? I am trying to double-check your PR, but I see some compilation issues. 

Here is the error I am getting locally:
```
Current allocation mode is local
Current file position is 14
Latexmk: Getting log file 'article.log'
Latexmk: Examining 'article.fls'
Latexmk: Examining 'article.log'
Latexmk: References changed.
Latexmk: 'pdflatex': source file 'article.bbl' doesn't exist. I'll try making it...
------------
Running 'make "article.bbl"'
------------
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 13 reference(s)
  Latex failed to resolve 28 citation(s)
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 0.05078125
      Refer to 'article.log' for details
```

**Comment by din0s** [comment]
Hi @SharathRaparthy, sorry for the delayed reply.

We've been trying to find out whether there is something wrong, but as far as we can tell, the final PDF is being generated correctly and we pass the CI build. However, I checked the build.log [(pastebin link)](https://pastebin.com/Pd5U5KpE) and I can also see warnings about missing references as you pointed out (lines 247 - 427 in attached log file).

This seems like a weird behavior of pdflatex [(stackexchange answer)](https://tex.stackexchange.com/a/354218) where it tries to include the bibliography before biber has generated the .bbl file, as indicated by the biblatex warnings (lines 433 - 440 in attached log file). When this does happen later on in the build process (lines 453 - 493), I believe that pdflatex is instructed to re-run and it is able to find all required files (including bibliography) to generate the final camera-ready PDF.

Is my understanding correct, or is there something we need to fix? I've checked other PRs and I cannot see a difference in how they are importing the bibliography...

**Comment by koustuvsinha** [comment]
Works perfectly on my end.

**Comment by SharathRaparthy** [comment]
Thanks for the reply @din0s ! There was an issue from my end and hence I was not able to generate the PDF. But now, I just recompiled and the PDF looks great to me. Sorry for any inconvenience caused.

**Pull request merged**
