### PR TITLE
luisa2022thompson

### PR DESCRIPTION
**Pull request by andrazdeluisa**
## Project Name

luisa2022thompson

## Compiled PDF

[Compiled Pdf](2021/luisa2022thompson/journal/article.pdf)

## Metadata Checklist

Ensure that you have added the following metadata information (put an x to the checkbox items) in `<paper_citekey>/journal/metadata.yaml`.

- [x] `title` field exists and it starts with `[Re] `.
- [x] `authors` contain author information with affiliations.
- [x] [ORCID id](https://orcid.org/) is provided for authors.
- [x] One contact author is added using `*`.
- [x] Github `url` is provided in `code` section.
- [x] [SWH identifier](https://archive.softwareheritage.org/save/) is provided in `swh`.
- [x] `replication` section is populated with the necessary information about the paper you reproduced.
- [x] `abstract` field is populated with your paper abstract (including double quotes)
- [x] `domain` should contain "ML Reproducibility Challenge 2021"
- [x] `review` section contains the url to the OpenReview forum of your paper.
- [x] Fields `contributors`, `dates`, `article` and `journal` are kept blank, as those will be populated by the Area Chairs / ReScience editors.

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Possible issue with `enumerate` package as noted in #91

**Comment by andrazdeluisa** [comment]
Hi, am I supposed to do something about it? Asking because I don't encounter any compilation issues when I do it locally on my laptop.

**Comment by andrazdeluisa** [comment]
Hi @koustuvsinha, may I repeat the above question, am I supposed to try to solve this compilation issue? I saw most of the other pull requests were already accepted and wouldn't like to be left out

Kind regards, Andraž

**Comment by koustuvsinha** [comment]
Closing this as @andrazdeluisa has opened a new PR #112

**Pull request closed without merging**
